name: 'PNPM Setup'

description: 'Sets PNPM up for CI'

runs:
  using: 'composite'

  steps:
    - name: ðŸ—ï¸ Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: ðŸ“¦ Install PNPM
      uses: pnpm/action-setup@v2
      with:
        run_install: false

    - name: ðŸ“ Get PNPM store directory
      id: pnpm-store
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: ðŸ’¾ Setup PNPM cache
      with:
        path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: ðŸ§° Install dependencies
      shell: bash
      run: pnpm install
